
GET http://localhost:8000/movies
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFzaG9rIiwiaWF0IjoxNzI2NjU2MDc1fQ.pTJl2ijJwwHysdmqSxUqnmLcyf4piBF1unDho6sUq04

###


# https://backend-api-1-ebqt.onrender.com/userDetails
POST http://localhost:8000/register
Content-Type: application/json

{
    "username":"Ashok",
    "gender":"Male",
    "password":"ashok@2024"
}

###

POST http://localhost:8000/login
Content-Type: application/json

{
    "username":"Ashok",
    "password":"ashok@2024"
}