
GET http://localhost:5000/userDetails

###

POST http://localhost:5000/register
Content-Type: application/json

{
    "username":"Ashok",
    "gender":"Male",
    "password":"ashok@2024"
}

###

POST http://localhost:5000/login
Content-Type: application/json

{
    "username":"Ashok",
    "password":"ashok@2024"
}