
GET http://localhost:8000/userDetails

###


# https://backend-api-1-ebqt.onrender.com/userDetails
POST http://localhost:8000/register
Content-Type: application/json

{
    "username":"Ashok",
    "gender":"Male",
    "password":"ashok@2024"
}

###

POST http://localhost:8000/login
Content-Type: application/json

{
    "username":"Ashok",
    "password":"ashok@2024"
}